# Generated by Django 3.1.12 on 2025-04-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undrid', '0002_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='researcher',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researched_articles', to='undrid.contributor'),
        ),
    ]
